### ISSUE TITLE
BatchSipAssemblerWithCallback returns unusable SIP files

### ISSUE THREAD

**Issue by jur-clerkx** [Enterprise-Content-Management/infoarchive-sip-sdk#39]
When using the `BatchSipAssemblerWithCallback` class the assembler returns invalid SIP packages. These packages have invalid settings for the seqno and the islast fields. Error code:
`Aip reception fails with code ERROR due to: 'Error(s) during Aip validation:\naip : Error exceedingSeqNo, Seqno:2 is > to max: 1 \n'. Consult aip logs.`

With the current implementation, it isn't possible to use the Callback to directly ingest the SIP package and delete the file directly afterwards to reduce memory usage when archiving big amounts of data. Is there another way to do this, or should the implementation of the `BatchSipAssemblerWithCallback` class be changed to make this implementation possible?

**Comment by RaySinnema** [comment]
Hi Jur,

Thanks for reporting this.

I'm trying to reproduce the second issue and have added `WhenAssemblingSipsInBatches.shouldBeAbleToDeleteFileFromCallback()`. This test passes on Linux and Windows. Can you please give more details about what isn't working?


Thanks,
Ray

**Comment by RaySinnema** [comment]
The `seqno` and `is_last` fields are controlled by the _Data Submission Session_ (DSS). The [lab project](https://github.com/Enterprise-Content-Management/infoarchive-sip-sdk-lab) explains how to make it so that each SIP is in its own DSS ([exercise 6](https://github.com/Enterprise-Content-Management/infoarchive-sip-sdk-lab/blob/master/src/test/java/com/opentext/ia/sipsdk/lab/Answer6.java)) or that all the SIPs are in the same DSS ([exercise 5](https://github.com/Enterprise-Content-Management/infoarchive-sip-sdk-lab/blob/master/src/test/java/com/opentext/ia/sipsdk/lab/Answer5.java)).

How are you using DSSes for your SIPs?

**Comment by jur-clerkx** [comment]
I'm using the PackagingInformation as showed in exercise 5.
What I'm trying to achieve is instead of building one very big SIP package, which will take up a lot of memory on the client PC, is using the `BatchSipAssemblerWithCallback` to directly ingest the package inside the callback method and then deleting it, while the other items are still being added to the assembler. 

However, on ingesting the packages the `BatchSipAssemblerWithCallback` creates (in the callback as well as after calling the `BatchSipAssemblerWithCallback.end()` method), the InfoArchive server returns the error described above. When using the normal `BatchSipAssembler` this problem doesn't occur, but this class isn't suitable for my use case. It seems that when using the `BatchSipAssemblerWithCallback` class to assemble the SIP packages, the `seqno` and `is_last` fields aren't set to the correct values.

I'm using the following classes for the full process:

- `PackagingInformation.builder()...` 
- `XMLPdiAssembler`
- `BatchSipAssemblerWithCallback`
- `ArchiveClient.ingest()` to send the package to the server

**Comment by RaySinnema** [comment]
> instead of building one very big SIP package, which will take up a lot of memory on the client PC

Do you mean RAM? The SDK makes sure to not keep things in memory when not needed, so it shouldn't use a lot of RAM. The only thing kept in RAM that increases over time while building a SIP, is the PDI. You can write that to disk instead of RAM by using the `SipAssembler` constructor that takes a `pdiBufferSupplier`. Instead of passing in `new DataBufferSupplier<>(MemoryBuffer.class)`, use a `FileBuffer`. Obviously, that will be slower.

**Comment by jur-clerkx** [comment]
I meant memory as in disk space. There is a possibilty that my application will require to migrate data from an application that uses more disk space than the client machine has available.

**Comment by RaySinnema** [comment]
Is there any reason that these SIPs must be part of the same DSS?

**Comment by jur-clerkx** [comment]
Offcourse it's possible to create a workaround and just create SIPs with seperate DSSs. However, this does not take away that the `BatchSipAssemblerWithCallback` doesn't function properly (unless my implementation is incorrect).

The usage of the class would greately improve the ingestion of big SIPs that require to be part of the same DSS as you could start ingestion to the server while still generating the other parts of the package. I'll try changing my code to use the `OneSipPerDssPackagingInformationFactory` to see if this fixes the error.

**Comment by RaySinnema** [comment]
I fixed the issue and also added a new class `ActiveArchiver` that should make it easier to start with active archiving scenarios.
