### ISSUE TITLE
Declarative Configuration(SIP Archiving) - NullPointerException during SIP ingestion

### ISSUE THREAD

**Issue by clementjosh** [Enterprise-Content-Management/infoarchive-sip-sdk#45]
ingest applications/Driver --from data
17:03:08.503 ERROR - Command failed java.lang.IllegalStateException: java.lang.Exception: Cannot upload the file: 'D:\StudyMaterial\infoarchive-ep4\infoarchive\examples\applications\Driver\data\eas_pdi.zip'. Please, contact 'logs/iashell/iashell.log' for additional information.
400 errors:
aip Aip reception fails with code ERROR due to: 'java.lang.NullPointerException: null data supplied'. Consult aip logs.
 on POST request for "http://localhost:8765/systemdata/applications/33185a18-7e86-41a3-baa0-a73e32d500e2/aips"

**Comment by IgorNikiforov** [comment]
Hello @clementjosh,

Thank you for the reporting the case. 

The root cause of the issue looks to be on client side (see 4xxx kind of REST response). If to be more specific, the issue in SIP file you are trying to ingest or in application configuration you installed. Please, make sure that your SIP file satisfy requirements and application has all required configuration objects defined. You may use out-of-the-box applications provided in examples to compare with you SIP and application configuration. 

At the same time it looks for me, that there is a space for improvment on InfoArhive side due to we should not throw NPE, but instead have a check on the required field and response with proper message.
In order to have the message improved, I believe, you need to contact InfoArchive support as far as the NPE fix and message improvement is not related to that Git 'infoarchive-sip-sdk' project.

When contacting InfoArchive support, please provide within the case:
 - customer name
 - the InfoArchive version number that you are using 
 - IA server side logs
 - and sample application configuration
 - and sample SIP that you are trying to ingest

Thank you.
